name: Deploy To Itch.io
on:
  workflow_dispatch: 
        
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-to-itchio:
    name: Test Current Build in Unity
    runs-on: ubuntu-latest
    strategy: 
        fail-fast: false
        matrix: 
          targetPlatform:
            - StandaloneWindows # Build a Windows standalone.
            - WebGL # WebGL.
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      
      - name : Cache Repository
        uses: actions/cache@v3
          with:
            path: Library
            key: Library-${{ matrix.targetPlatform }}
            restore-keys: Library-
              
#      - name: Cache Unity Build Artifacts
#        uses: actions/cache@v5
#        with:
#          path: Builds
#          key: {{runner.os }}-${{ hashFiles('Build/**') }}
          
            
#      - name: Unity - Test runner
#          uses: game-ci/unity-test-runner@v4.3.1
#          env:
#            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
#            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
#          with:
#            projectPath: Assets
#            githubToken: ${{ secrets.GH_TOKEN }}
      
      - name: Build Unity Artifact
        uses: game-ci/unity-builder@v4.8.1
        id: buildStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{matrix.targetPlatform}}
  
          
          
      - run: echo "Project Version ${{steps.buildStep.outputs.buildVersion}}"
        
      - name : Upload Artifact
        uses: actions/upload-artifact@v4
          with:
           name: Build-${{ matrix.targetPlatform }}
           path: build/${{ matrix.targetPlatform }}