name: Generate Documnetaion

on: 
  workflow_dispatch:
    inputs:
      version: 
        description: 'Documentation Version (optional)'
        required: false
        default: 'latest'
      

permissions: 
  contents: write
  pages: write
  id-token: write

jobs:
  generate-docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Doygen & Dependencies
        run : | 
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
      
      - name: Generate Doxygen
        run: | 
            doxygen Doxyfile
      
      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{secrets.GH_TOKEN}}
          publish_dir: ./public
          publish_branch: docs
          enable_jekyll: true
          force_orphan: true

      - name: Create Summary
        if: always()
        run: |
          echo "## 📚 Documentation Generated" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Generated at:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "🔗 [View Documentation](https://$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]').github.io/$(echo ${{ github.event.repository.name }}))" >> $GITHUB_STEP_SUMMARY
      
  
            

